from django.core.management.base import BaseCommand
from django.utils.text import slugify
from metrics.models import MetricNode


def make_slug(name):
    return slugify(name)[:200]


def create_node(data, parent=None):
    children = data.pop('children', [])
    slug = make_slug(data['name'])
    node, _ = MetricNode.objects.update_or_create(
        slug=slug,
        defaults={**data, 'parent': parent},
    )
    for child in children:
        create_node(child, parent=node)
    return node


TREE = {
    'name': 'North Star',
    'icon': '⭐',
    'category': 'root',
    'is_group': True,
    'order': 0,
    'short_description': 'The single metric that best captures the core value your product delivers to users.',
    'full_description': 'The North Star Metric (NSM) is the one number that best reflects the value your product delivers — and is most predictive of long-term business success. It sits at the top of the metrics tree and is supported by all downstream pillars: Growth, Activation, Retention, Engagement, Revenue, Satisfaction, and Quality. Examples: Spotify → Monthly Active Streamers, Airbnb → Nights Booked, Slack → Messages Sent per Active User, Duolingo → Daily Active Learners.',
    'formula': 'Varies by product. Choose the metric that best answers: "If this number grows, are we delivering more value to more users?"',
    'why_it_matters': 'Without a clear North Star, teams optimize local metrics at the expense of the whole. The NSM aligns PMs, engineers, designers, and business stakeholders on what truly matters — making it the foundation for all OKRs and roadmap decisions.',
    'how_to_improve': 'Choose a metric that reflects user value, not just revenue. Break it into its drivers using this tree. Run monthly cross-pillar reviews to find the weakest link constraining your North Star.',
    'benchmark': '',
    'children': [
        # ─── GROWTH ────────────────────────────────────────────────────────────
        {
            'name': 'Growth & Acquisition',
            'icon': '📈',
            'category': 'growth',
            'is_group': True,
            'order': 0,
            'short_description': 'How effectively your product attracts and converts new users.',
            'full_description': 'Growth & Acquisition covers the entire funnel from brand awareness through traffic, landing-page conversion, and the first sign-up. Strong acquisition without good retention is like filling a leaky bucket — both must work in tandem.',
            'formula': '',
            'why_it_matters': 'Without a steady stream of new users, natural churn will erode your user base. Acquisition is the top-of-funnel engine that feeds all downstream metrics.',
            'how_to_improve': 'Map every acquisition channel, measure CAC per channel, and double down on the best LTV:CAC ratio.',
            'benchmark': '',
            'children': [
                {
                    'name': 'Unique Visitors',
                    'icon': '👥',
                    'category': 'growth',
                    'is_group': False,
                    'order': 0,
                    'short_description': 'Distinct individuals who visited your product in a period.',
                    'full_description': 'Unique visitors represents the true reach of your product. Unlike sessions, this deduplicates repeat visits from the same person, giving a clean measure of audience size. Flat or declining unique visitors is an early warning that new discovery has stalled even if total sessions look healthy.',
                    'formula': 'Count of distinct user_id or device_id per period',
                    'why_it_matters': 'Growing unique visitors confirms your reach is expanding. Stagnation here means acquisition channels are saturating.',
                    'how_to_improve': 'Invest in SEO, paid acquisition, and content marketing. Measure net-new visitors vs. return visitors by channel.',
                    'benchmark': 'Early-stage: 1K–10K/mo. Growth-stage: 100K+/mo. Healthy YoY growth: 15–30%.',
                },
                {
                    'name': 'Traffic Source Mix',
                    'icon': '🗺️',
                    'category': 'growth',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'Breakdown of users by channel: organic, paid, direct, referral, social.',
                    'full_description': 'Traffic source mix shows the proportion of users from each channel. Over-reliance on a single channel (e.g. paid ads) creates fragility. A diverse mix with growing organic share signals compounding brand authority.',
                    'formula': 'Channel % = (Visitors from channel / Total visitors) × 100',
                    'why_it_matters': 'Algorithm changes or budget cuts can devastate a single-channel product overnight. Organic and referral channels compound at near-zero marginal cost.',
                    'how_to_improve': 'Build SEO moats with evergreen content. Create viral loops for referral traffic. Monitor channel-level CAC.',
                    'benchmark': 'Healthy B2B SaaS: 40–60% organic. Consumer apps: heavier social and paid mix early on.',
                },
                {
                    'name': 'Visitor-to-Sign-up Rate',
                    'icon': '✍️',
                    'category': 'growth',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'Percentage of visitors who create an account.',
                    'full_description': 'This is the critical gateway metric — everything downstream (activation, retention, revenue) only applies to users who crossed this threshold. Small improvements here multiply across all the traffic you already pay for.',
                    'formula': 'Sign-up Rate = (New sign-ups / Unique visitors) × 100',
                    'why_it_matters': 'Doubling conversion rate is equivalent to doubling traffic at zero extra acquisition cost.',
                    'how_to_improve': 'Reduce sign-up form fields. Add social login. A/B test value proposition copy. Add trust signals above the fold.',
                    'benchmark': 'Consumer apps: 2–5%. B2B SaaS: 1–3% of all visitors.',
                },
                {
                    'name': 'CAC (Customer Acquisition Cost)',
                    'icon': '💸',
                    'category': 'growth',
                    'is_group': True,
                    'order': 3,
                    'short_description': 'Total cost to acquire one new paying customer.',
                    'full_description': 'CAC = total sales & marketing spend divided by new customers acquired. It must always be evaluated against LTV. CAC by channel reveals which channels are most efficient and deserve more investment.',
                    'formula': 'CAC = Total Sales & Marketing Spend / New Customers Acquired',
                    'why_it_matters': 'CAC > LTV means every new customer destroys value. Understanding per-channel CAC guides budget allocation.',
                    'how_to_improve': 'Improve conversion rates. Optimize ad creative. Invest in SEO and referral. Build product-led growth loops.',
                    'benchmark': 'LTV:CAC ≥ 3:1 is the standard benchmark. Payback under 12 months is healthy.',
                    'children': [
                        {
                            'name': 'Paid CAC',
                            'icon': '💳',
                            'category': 'growth',
                            'is_group': False,
                            'order': 0,
                            'short_description': 'Cost to acquire a customer through paid channels only.',
                            'full_description': 'Paid CAC isolates channels such as Google Ads, Meta, LinkedIn, and sponsorships. It is typically higher than blended CAC. Tracking it separately enables precise channel ROI analysis.',
                            'formula': 'Paid CAC = Paid Ad Spend / Customers from Paid Channels',
                            'why_it_matters': 'Paid channels scale fast but margins compress as spend increases. Knowing Paid CAC helps decide when to scale or pause paid spend.',
                            'how_to_improve': 'Improve ad creative. Tighten audience targeting. Increase landing page CVR.',
                            'benchmark': 'B2B SaaS: $200–$1,000+. Consumer apps: $2–$50 per install.',
                        },
                        {
                            'name': 'Organic CAC',
                            'icon': '🌿',
                            'category': 'growth',
                            'is_group': False,
                            'order': 1,
                            'short_description': 'Cost to acquire a customer through organic channels.',
                            'full_description': 'Organic CAC accounts for content, SEO, and community investment divided by customers from those channels. It is lower than paid CAC and compounds over time — content written today drives customers for years.',
                            'formula': 'Organic CAC = (Content + SEO + Community Spend) / Customers from Organic',
                            'why_it_matters': 'Growing organic share lowers blended CAC and signals product-market fit. People are finding you without being told to.',
                            'how_to_improve': 'Invest in SEO content. Build referral programs. Cultivate community and brand advocates.',
                            'benchmark': 'Approaches $0 marginal cost at scale for well-established organic channels.',
                        },
                    ],
                },
                {
                    'name': 'Viral Coefficient (K-Factor)',
                    'icon': '🦠',
                    'category': 'growth',
                    'is_group': False,
                    'order': 4,
                    'short_description': 'How many new users each existing user brings in through referrals.',
                    'full_description': 'K > 1 means exponential growth through pure word of mouth. K < 1 (typical) means referral augments but doesn\'t replace paid growth. Even K = 0.3–0.5 meaningfully extends your acquired users by reducing effective CAC.',
                    'formula': 'K = (Invites sent per user) × (Conversion rate of invites)',
                    'why_it_matters': 'Even a small K-Factor dramatically lowers effective CAC. It is one of the few metrics that can make growth exponential rather than linear.',
                    'how_to_improve': 'Add referral bonuses. Design collaborative features requiring invites. Make product outputs shareable.',
                    'benchmark': 'K > 1 is viral. K = 0.3–0.7 is strong for SaaS. Aim for K > 0.5 in consumer apps.',
                },
            ],
        },
        # ─── ACTIVATION ────────────────────────────────────────────────────────
        {
            'name': 'Activation',
            'icon': '✅',
            'category': 'activation',
            'is_group': True,
            'order': 1,
            'short_description': 'How quickly new users experience the core value of your product.',
            'full_description': 'Activation is the phase between sign-up and the Aha Moment — the first time a user experiences meaningful value. It is arguably the highest-leverage stage in the funnel: fixing activation creates a compounding effect across retention, LTV, and effective CAC.',
            'formula': '',
            'why_it_matters': 'Improving activation is often the highest-ROI PM investment. More activated users → better retention → higher LTV → lower effective CAC.',
            'how_to_improve': 'Map the activation funnel step by step. Find the biggest drop-off. Use in-app guides and smart onboarding to get users to value faster.',
            'benchmark': '',
            'children': [
                {
                    'name': 'Activation Rate',
                    'icon': '⚡',
                    'category': 'activation',
                    'is_group': False,
                    'order': 0,
                    'short_description': 'Percentage of new sign-ups who complete the key activation milestone.',
                    'full_description': 'Activation rate measures the fraction of new users who complete the critical action that predicts long-term retention — your defined Aha Moment. The exact event varies by product: first message sent, first project created, first integration connected.',
                    'formula': 'Activation Rate = (Users who completed activation event / Total new sign-ups) × 100',
                    'why_it_matters': 'Doubling activation from 10% to 20% is equivalent to doubling your paid acquisition budget with no extra spend.',
                    'how_to_improve': 'First define the activation event via retention cohort analysis. Then optimize the path: personalize onboarding, remove friction steps, add progressive education.',
                    'benchmark': 'Consumer apps: 20–40%. B2B SaaS: 30–60%. Great: 50%+ for SaaS.',
                },
                {
                    'name': 'Time to First Value (TTFV)',
                    'icon': '⏱️',
                    'category': 'activation',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'How long it takes a new user to experience meaningful product value after sign-up.',
                    'full_description': 'TTFV measures elapsed time from sign-up to the Aha Moment. Shorter is almost always better. User attention and motivation peak right after sign-up — every extra minute increases abandonment probability.',
                    'formula': 'TTFV = Timestamp of first value event − Timestamp of sign-up',
                    'why_it_matters': 'Products that deliver value in seconds dramatically outperform those that take hours. TTFV is a direct measure of onboarding efficiency.',
                    'how_to_improve': 'Reduce onboarding steps. Pre-populate templates. Use progressive disclosure — show main value immediately, ask for details later.',
                    'benchmark': 'Consumer apps: aim for value within seconds–2 min. B2B SaaS: under 10 min is excellent.',
                },
                {
                    'name': 'Onboarding Completion Rate',
                    'icon': '🎓',
                    'category': 'activation',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'Percentage of users who finish the guided onboarding flow.',
                    'full_description': 'Tracks how many users complete your onboarding experience — wizard, checklist, or guided tour. Completion is a strong predictor of activation and first-week retention. Per-step drop-off analysis pinpoints exactly where users bail out.',
                    'formula': 'Onboarding Completion = (Users who completed all steps / Users who started) × 100',
                    'why_it_matters': 'Low completion signals your onboarding is too long, confusing, or misaligned with expectations. Each identified drop-off step is a concrete improvement opportunity.',
                    'how_to_improve': 'Analyze per-step drop-off. Remove non-essential steps. Show progress indicators. Allow skipping already-completed steps.',
                    'benchmark': 'Good: 50–70%. Great: 70–85%+.',
                },
                {
                    'name': 'Aha Moment Conversion',
                    'icon': '💡',
                    'category': 'activation',
                    'is_group': False,
                    'order': 3,
                    'short_description': 'Percentage of users who reach the specific moment that predicts long-term retention.',
                    'full_description': 'The Aha Moment is the specific action that correlates most strongly with becoming a retained customer. Famous examples: Facebook\'s "7 friends in 10 days," Slack\'s "2,000 messages sent." Discover it by analyzing what D30 retained users did in week 1 that churned users didn\'t.',
                    'formula': 'Aha Moment CVR = (Users who reached Aha Moment / Total sign-ups) × 100',
                    'why_it_matters': 'Identifying and driving users to the Aha Moment is the single highest-impact product intervention for most early-stage products.',
                    'how_to_improve': 'Run cohort analysis: compare D30 retention of users who did vs. didn\'t perform each action in week 1. Redesign onboarding around the winning action.',
                    'benchmark': 'Even moving from 20% to 30% Aha Moment CVR can double your retained user base.',
                },
                {
                    'name': 'Product-Qualified Leads (PQL)',
                    'icon': '🏆',
                    'category': 'activation',
                    'is_group': False,
                    'order': 4,
                    'short_description': 'Free or trial users who have used the product enough to signal buying intent.',
                    'full_description': 'A PQL is a user who has reached a predefined usage threshold that signals sales-readiness — e.g., "used 5 core features in 14 days" or "hit the usage limit." PQLs are identified by in-product behavior, not form fills. They are the North Star metric for Product-Led Growth (PLG) companies.',
                    'formula': 'PQL Rate = (Users meeting PQL criteria / Total active free users) × 100',
                    'why_it_matters': 'PQLs convert to paid at 3–5× the rate of MQLs because they\'ve already proven value to themselves. Increasing PQL rate is the most direct revenue lever for PLG companies.',
                    'how_to_improve': 'Define PQL criteria from conversion data. Optimize product experience to drive PQL behavior. Alert sales when a user reaches PQL status.',
                    'benchmark': 'PQL-to-paid conversion of 15–25% is strong. PQLs should drive 50%+ of new revenue in pure PLG products.',
                },
            ],
        },
        # ─── RETENTION ─────────────────────────────────────────────────────────
        {
            'name': 'Retention',
            'icon': '🔄',
            'category': 'retention',
            'is_group': True,
            'order': 2,
            'short_description': 'How well your product keeps users coming back over time.',
            'full_description': 'Retention is the most consequential pillar of product health. It measures whether users who experienced your product once choose to return. Poor retention turns growth into a treadmill — you constantly replace churned users without growing. Strong retention compounds, creating a growing base of loyal users.',
            'formula': '',
            'why_it_matters': 'A 5% increase in retention can increase profits by 25–95% (Bain & Company). Retained users spend more, cost less to serve, and refer others.',
            'how_to_improve': 'Improve activation first. Build habit loops. Use re-engagement emails and push. Identify at-risk users early. Continuously improve core product value.',
            'benchmark': '',
            'children': [
                {
                    'name': 'Day 1 Retention (D1)',
                    'icon': '1️⃣',
                    'category': 'retention',
                    'is_group': False,
                    'order': 0,
                    'short_description': 'Percentage of users who return the day after first use.',
                    'full_description': 'D1 retention is the most sensitive leading indicator of onboarding quality. Users who don\'t return on Day 1 almost never become long-term retained users. It is a direct reflection of first-session quality.',
                    'formula': 'D1 Retention = (Users who used product on Day 1 after sign-up / Users who signed up) × 100',
                    'why_it_matters': 'D1 sets the ceiling for all downstream retention. You cannot have great D30 without first fixing D1.',
                    'how_to_improve': 'Improve the first session dramatically. Send a well-timed welcome notification. Ensure users complete at least one meaningful action before leaving.',
                    'benchmark': 'Consumer apps: great is 40%+. Mobile games: 30–40%. B2B SaaS: 50–70%.',
                },
                {
                    'name': 'Day 7 Retention (D7)',
                    'icon': '7️⃣',
                    'category': 'retention',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'Percentage of users who return within the first week.',
                    'full_description': 'By Day 7, users have had time to form initial impressions and decide whether the product fits their workflow. D7 is a key habit-formation checkpoint and a reliable predictor of D30 retention.',
                    'formula': 'D7 Retention = (Users active on Day 7 / Users who signed up) × 100',
                    'why_it_matters': 'If users don\'t return by Day 7, they rarely return at all. Strong D7 retention proves genuine value and workflow fit.',
                    'how_to_improve': 'Send personalized feature tips between D1 and D7. Use behavior-triggered emails. Optimize the second-session experience.',
                    'benchmark': 'Consumer apps: great is 20%+. B2B tools: 30–50%.',
                },
                {
                    'name': 'Day 30 Retention (D30)',
                    'icon': '📅',
                    'category': 'retention',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'Percentage of users who return within the first month.',
                    'full_description': 'D30 retention is the industry-standard measure of product-market fit and value proposition durability. Users retained at 30 days have formed genuine habits or business dependencies. It is the primary driver of LTV and the most-watched retention metric by investors.',
                    'formula': 'D30 Retention = (Users active on Day 30 / Users who signed up) × 100',
                    'why_it_matters': 'Improving D30 by even 5pp can double the effective lifetime of a user and dramatically improve LTV.',
                    'how_to_improve': 'Identify what activated users do in week 1 that retained users do but churned users don\'t. Build habit-driving features (streaks, reminders). Run win-back campaigns at Days 14–20.',
                    'benchmark': 'Consumer apps: 10–20% average; 20–30% great; 30%+ exceptional. B2B SaaS: 50–70% monthly.',
                },
                {
                    'name': 'DAU / WAU / MAU',
                    'icon': '📆',
                    'category': 'retention',
                    'is_group': False,
                    'order': 3,
                    'short_description': 'Daily, Weekly, and Monthly Active Users — the pulse of product usage.',
                    'full_description': 'DAU, WAU, and MAU count distinct users performing at least one meaningful action in each time window. They are the foundational engagement metrics from which most others are derived. Choose the right granularity for your product\'s expected usage frequency.',
                    'formula': 'DAU/WAU/MAU = Unique users with ≥1 meaningful action in respective period',
                    'why_it_matters': 'Active user counts are the clearest measure of real product reach. Sudden DAU drops indicate incidents. Sustained MAU growth confirms acquisition + retention are working.',
                    'how_to_improve': 'Improve the core loop driving return visits. Add notifications at optimal times. Create natural daily or weekly use cases.',
                    'benchmark': 'Consumer social: target daily. Productivity SaaS: WAU/MAU. Enterprise: MAU typical.',
                },
                {
                    'name': 'DAU/MAU Ratio (Stickiness)',
                    'icon': '🧲',
                    'category': 'retention',
                    'is_group': False,
                    'order': 4,
                    'short_description': 'Proportion of monthly users who use the product daily — measures habit strength.',
                    'full_description': 'The DAU/MAU ratio reveals how central your product is to daily life. Facebook maintains ~65–70% stickiness. A ratio of 50% means an average monthly user visits every other day. It is a pure signal of habit formation, independent of growth noise.',
                    'formula': 'Stickiness = (DAU / MAU) × 100',
                    'why_it_matters': 'High stickiness means your product has found a genuine daily job-to-be-done. Low stickiness despite high MAU means users visit sporadically and are at churn risk.',
                    'how_to_improve': 'Build habit loops: trigger → action → reward. Add daily value delivery (reports, feeds, streaks). Create recurring workflows that drive regular use.',
                    'benchmark': 'Consumer social: 50–70%. Productivity: 20–40%. Content apps: 25–40%. Under 10%: weak for most consumer products.',
                },
                {
                    'name': 'Churn Rate',
                    'icon': '📉',
                    'category': 'retention',
                    'is_group': True,
                    'order': 5,
                    'short_description': 'Percentage of users or revenue lost in a given period.',
                    'full_description': 'Churn is the complement of retention. A product churning 10% of users monthly loses over 70% of its user base in a year. Segmenting churn by cohort, plan, and channel reveals which users to prioritize in retention efforts.',
                    'formula': 'Churn Rate = (Users lost in period / Users at start of period) × 100',
                    'why_it_matters': 'Even with strong acquisition, high churn creates a growth ceiling. Reducing churn is often more capital-efficient than increasing acquisition.',
                    'how_to_improve': 'Conduct exit surveys. Identify churn patterns by stage and cohort. Build proactive health scoring. Offer pause or downgrade options before full cancellation.',
                    'benchmark': '',
                    'children': [
                        {
                            'name': 'Monthly User Churn',
                            'icon': '🚪',
                            'category': 'retention',
                            'is_group': False,
                            'order': 0,
                            'short_description': 'Percentage of active users who stop using the product each month.',
                            'full_description': 'Monthly user churn tracks the proportion of active users who do not return in the following month. Tracking monthly catches deterioration early before it becomes a revenue crisis.',
                            'formula': 'Monthly Churn = (Active in M who were inactive in M+1) / Active in M × 100',
                            'why_it_matters': '10% monthly churn means replacing your entire user base every 10 months — an unsustainable growth treadmill.',
                            'how_to_improve': 'Segment churned users by source, plan, and behavior. Build re-engagement campaigns triggered by declining usage signals.',
                            'benchmark': 'Consumer apps: 5–8% average; under 3% excellent. B2B SaaS: under 1% monthly.',
                        },
                        {
                            'name': 'Revenue Churn (MRR Churn)',
                            'icon': '💔',
                            'category': 'retention',
                            'is_group': False,
                            'order': 1,
                            'short_description': 'Percentage of MRR lost from cancellations and downgrades.',
                            'full_description': 'Revenue churn measures dollars lost from cancellations and downgrades as a % of total MRR. Net Revenue Churn accounts for expansion MRR — companies with negative net churn grow revenue from their existing base alone.',
                            'formula': 'Gross MRR Churn = (MRR lost from cancels + downgrades) / Beginning MRR × 100\nNet MRR Churn = (MRR lost − Expansion MRR) / Beginning MRR × 100',
                            'why_it_matters': 'Negative net MRR churn is the holy grail of SaaS — revenue grows even without new customers.',
                            'how_to_improve': 'Focus retention on high-value accounts. Build upsell motions for expansion MRR. Engage accounts showing usage decline before they cancel.',
                            'benchmark': 'Good gross MRR churn: under 1%/month. Best-in-class (Slack, Datadog): negative net churn.',
                        },
                        {
                            'name': 'Resurrection Rate',
                            'icon': '🔁',
                            'category': 'retention',
                            'is_group': False,
                            'order': 2,
                            'short_description': 'Percentage of previously churned users who return to the product.',
                            'full_description': 'Resurrection rate measures how many inactive users return without paid re-acquisition. Reactivated users carry lower acquisition cost and often higher intent. A high resurrection rate signals latent brand equity and product stickiness.',
                            'formula': 'Resurrection Rate = (Inactive users who became active / Total inactive users at period start) × 100',
                            'why_it_matters': 'Churned users represent sunk CAC. Resurrecting a fraction at near-zero cost meaningfully improves unit economics.',
                            'how_to_improve': 'Build win-back email campaigns at 2, 4, 8 weeks post-churn. Create re-engagement hooks around product updates. Use personalized outreach referencing past behavior.',
                            'benchmark': 'Good: 5–10% of churned users resurrect monthly. Great: 15%+.',
                        },
                    ],
                },
            ],
        },
        # ─── ENGAGEMENT ────────────────────────────────────────────────────────
        {
            'name': 'Engagement',
            'icon': '💡',
            'category': 'engagement',
            'is_group': True,
            'order': 3,
            'short_description': 'The depth and quality of how users interact with your product.',
            'full_description': 'Engagement metrics measure not just whether users return, but how deeply they use the product when they do. High engagement correlates with willingness to pay, referrals, and resistance to switching. A product with shallow engagement is vulnerable even if retention looks OK.',
            'formula': '',
            'why_it_matters': 'Highly engaged users convert to paid at higher rates, upgrade plans, and generate more referrals. They\'re harder to churn because the product is woven into their workflow.',
            'how_to_improve': 'Analyze which features the most engaged users adopt. Drive feature discovery via tooltips, empty states, and personalized recommendations.',
            'benchmark': '',
            'children': [
                {
                    'name': 'Sessions per User per Week',
                    'icon': '🔢',
                    'category': 'engagement',
                    'is_group': False,
                    'order': 0,
                    'short_description': 'How frequently users visit the product within a week.',
                    'full_description': 'Sessions per user per week is a frequency metric and a proxy for habit formation. Users who open a product 5× per week are far more retained and more likely to pay than once-a-week users.',
                    'formula': 'Sessions per User per Week = Total sessions in week / WAU',
                    'why_it_matters': 'Frequency is a leading indicator of habit. Improving session frequency is one of the most reliable ways to improve retention.',
                    'how_to_improve': 'Create multiple use cases to return. Add event-triggered notifications. Build streaks or recurring workflows that drive weekly use.',
                    'benchmark': 'Social apps: 7–20 sessions/week. Productivity: 3–7. Professional tools: 1–5.',
                },
                {
                    'name': 'Average Session Duration',
                    'icon': '⌛',
                    'category': 'engagement',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'Average time a user spends in the product per session.',
                    'full_description': 'Session duration must be interpreted contextually: longer sessions signal engagement in content/social apps but may indicate friction in task-completion tools. Always correlate with task completion rates and satisfaction data.',
                    'formula': 'Avg Session Duration = Total session time / Number of sessions',
                    'why_it_matters': 'For content apps, longer sessions mean more value and more ad inventory. For productivity apps, efficiency matters more than length.',
                    'how_to_improve': 'For engagement apps: add compelling content and recommendations. For productivity apps: ensure tasks complete efficiently — don\'t optimize for longer sessions at the cost of efficiency.',
                    'benchmark': 'Consumer social: 5–15 min. B2B SaaS: 10–30 min. Mobile games: 8–20 min.',
                },
                {
                    'name': 'Feature Adoption Rate',
                    'icon': '📋',
                    'category': 'engagement',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'Percentage of active users who have used a specific feature at least once.',
                    'full_description': 'Feature adoption rate is the first indicator of whether a feature is being discovered and used. Low adoption means users don\'t know it exists, don\'t understand its value, or find it too hard to reach. It helps PMs detect wasted investment early.',
                    'formula': 'Feature Adoption Rate = (Users who used feature ≥1x / Total active users) × 100',
                    'why_it_matters': 'Features nobody uses are liabilities — they add complexity and maintenance cost. High-value low-adoption features represent concrete improvement opportunities.',
                    'how_to_improve': 'Add contextual tooltips at the right moment. Surface the feature in the natural user workflow. Promote high-value features in onboarding and in-app messages.',
                    'benchmark': 'Core features: 50–80%. Secondary: 15–40%. Advanced/specialist: 5–20% is acceptable.',
                },
                {
                    'name': 'Feature Retention (Stickiness)',
                    'icon': '📌',
                    'category': 'engagement',
                    'is_group': False,
                    'order': 3,
                    'short_description': 'Percentage of users who continue using a feature repeatedly after first discovery.',
                    'full_description': 'Feature retention distinguishes features that are tried from features that are adopted. High adoption but low retention means the feature is being tried but not delivering lasting value — a clear signal for redesign.',
                    'formula': 'Feature Retention = Users who used feature in M and M+1 / Users who used feature in M × 100',
                    'why_it_matters': 'High feature retention means users integrate the feature into their workflow, driving overall product retention and upsell potential.',
                    'how_to_improve': 'Redesign the feature to deliver clear value on second and third use. Add reminders or triggers to bring users back. Create a progression path that increases value over time.',
                    'benchmark': 'Core features: 50–70% monthly retention. Peripheral: 20–40%. Under 20% suggests significant rethinking is needed.',
                },
                {
                    'name': 'Breadth of Feature Use',
                    'icon': '🌊',
                    'category': 'engagement',
                    'is_group': False,
                    'order': 4,
                    'short_description': 'Average number of distinct features used per active user.',
                    'full_description': 'Breadth of use measures how many different features each user engages with. Users who use more features are more deeply integrated into the product, have higher switching costs, and are more likely to be retained and to upgrade. It is a leading indicator of account expansion potential.',
                    'formula': 'Breadth of Use = Total distinct features used / Active users',
                    'why_it_matters': 'Single-feature users are at high churn risk if that one feature loses value. Multi-feature users are stickier, higher-LTV, and better candidates for expansion MRR.',
                    'how_to_improve': 'Map the feature discovery journey. Create cross-feature entry points. Use in-app recommendations to surface relevant complementary features based on current usage patterns.',
                    'benchmark': 'Aim to grow breadth of use over the first 90 days of a user\'s lifecycle. Retained users typically use 2–4× more features than churned users.',
                },
                {
                    'name': 'Core Action Completion Rate',
                    'icon': '✔️',
                    'category': 'engagement',
                    'is_group': False,
                    'order': 5,
                    'short_description': 'Percentage of active users who complete the most important product action.',
                    'full_description': 'Core action completion rate tracks the fraction of active users who complete the single most important action — the action that delivers the product\'s core value proposition. For task management: "task completed." For e-commerce: "purchase made." For learning: "lesson finished." This is the product\'s heartbeat metric.',
                    'formula': 'Core Action Completion = (Users who completed core action / Active users) × 100',
                    'why_it_matters': 'The core action is your product\'s reason for existing. If only a fraction of active users complete it, your product is failing its primary job at scale.',
                    'how_to_improve': 'Remove friction from the core action flow. Use progressive disclosure to simplify. Re-engage users who started but didn\'t complete the action.',
                    'benchmark': 'Aim for as high a percentage as possible. Benchmark against your own cohort trends quarter-over-quarter.',
                },
            ],
        },
        # ─── REVENUE ───────────────────────────────────────────────────────────
        {
            'name': 'Revenue & Monetization',
            'icon': '💰',
            'category': 'revenue',
            'is_group': True,
            'order': 4,
            'short_description': 'How effectively your product converts user value into sustainable business revenue.',
            'full_description': 'Revenue & Monetization answers: "Is this a viable business?" Strong engagement and retention only matter if the product successfully monetizes. PMs must understand unit economics to make correct decisions about pricing, feature investment, and growth spend.',
            'formula': '',
            'why_it_matters': 'Without revenue, even beloved products cannot survive. PMs who understand unit economics make better decisions about everything from roadmap to pricing to growth investment.',
            'how_to_improve': 'Optimize pricing pages and payment flows. Experiment with pricing models (freemium, trial, usage-based). Improve PQL conversion. Build expansion revenue mechanics.',
            'benchmark': '',
            'children': [
                {
                    'name': 'MRR (Monthly Recurring Revenue)',
                    'icon': '💵',
                    'category': 'revenue',
                    'is_group': True,
                    'order': 0,
                    'short_description': 'Total predictable monthly revenue from active subscriptions.',
                    'full_description': 'MRR is the normalized monthly revenue from all active subscriptions. It is the North Star financial metric for subscription businesses and the primary input to ARR (MRR × 12). MRR growth rate signals whether the business is accelerating or decelerating.',
                    'formula': 'MRR = Sum of all active subscription values normalized to monthly',
                    'why_it_matters': 'MRR drives valuation (5–15× ARR for SaaS), determines growth investment levels, and signals whether the business model works.',
                    'how_to_improve': 'Grow through 4 levers: New MRR (more conversions), Expansion MRR (upsells), reducing Churned MRR, recovering Contraction MRR (preventing downgrades).',
                    'benchmark': 'World-class SaaS: Triple-Triple-Double-Double-Double early-stage growth rule. $1M ARR in year 1 signals strong PMF.',
                    'children': [
                        {
                            'name': 'New MRR',
                            'icon': '🆕',
                            'category': 'revenue',
                            'is_group': False,
                            'order': 0,
                            'short_description': 'Revenue from brand new paying customers this month.',
                            'full_description': 'New MRR is the revenue from first-time paying customers. It is the output of your acquisition and conversion funnel and the primary growth lever for early-stage companies.',
                            'formula': 'New MRR = Sum of MRR from customers making their first payment this month',
                            'why_it_matters': 'New MRR must exceed Churned MRR for net revenue growth. Tracking monthly shows acquisition and conversion machine effectiveness.',
                            'how_to_improve': 'Improve free-to-paid CVR. Reduce payment flow friction. Create time-sensitive upgrade triggers. Offer annual plan discounts.',
                            'benchmark': 'New MRR must consistently outpace Churned MRR for the business to grow.',
                        },
                        {
                            'name': 'Expansion MRR',
                            'icon': '📦',
                            'category': 'revenue',
                            'is_group': False,
                            'order': 1,
                            'short_description': 'Revenue from existing customers who upgraded or expanded usage.',
                            'full_description': 'Expansion MRR comes from upsells, plan upgrades, seat additions, or usage overages. Its CAC is near zero — it comes from customers you already have. Growing expansion MRR is a sign of genuine value delivery and effective monetization design.',
                            'formula': 'Expansion MRR = Sum of MRR increases from existing customers this month',
                            'why_it_matters': 'Companies with Expansion MRR exceeding Churned MRR achieve negative net churn — the revenue base grows even without new customers.',
                            'how_to_improve': 'Design natural upgrade triggers (usage limits, team invitations, power features). Build in-app upsell prompts at high-engagement moments.',
                            'benchmark': 'Best-in-class SaaS: expansion MRR exceeds churned MRR. Aim for expansion to represent 30–50% of new MRR at scale.',
                        },
                        {
                            'name': 'Churned MRR',
                            'icon': '❌',
                            'category': 'revenue',
                            'is_group': False,
                            'order': 2,
                            'short_description': 'Revenue lost from cancellations and downgrades this month.',
                            'full_description': 'Churned MRR is the revenue permanently lost from cancelled subscriptions and plan downgrades. Unlike user churn, revenue churn is weighted by account value — losing one $500/mo account matters more than losing five $20/mo accounts.',
                            'formula': 'Churned MRR = Sum of MRR from cancellations + MRR reduction from downgrades',
                            'why_it_matters': 'If Churned MRR equals New MRR, you\'re on a treadmill — working hard but not growing. Reducing churned MRR has the same P&L impact as adding that amount in New MRR, at a fraction of the cost.',
                            'how_to_improve': 'Proactively identify at-risk accounts with health scores. Invest in customer success. Implement save flows offering pause/downgrade before cancellation.',
                            'benchmark': 'Target: <1% gross MRR churn/month. Best-in-class: 0.3–0.5% monthly.',
                        },
                    ],
                },
                {
                    'name': 'Customer LTV',
                    'icon': '♾️',
                    'category': 'revenue',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'Total revenue expected from a customer over their entire relationship with your product.',
                    'full_description': 'LTV (Lifetime Value) is total expected revenue per customer. It is the fundamental unit economics input. LTV is driven by three factors: revenue per period (ARPU), gross margin %, and customer lifespan (1 / churn rate).',
                    'formula': 'LTV = ARPU × Gross Margin % / Monthly Churn Rate',
                    'why_it_matters': 'LTV determines how much you can afford to spend on acquisition. A high LTV gives competitive advantage — you can outbid competitors in ad auctions, partnerships, and distribution deals.',
                    'how_to_improve': 'Increase ARPU (better pricing, upsells). Improve gross margin. Reduce churn (longer lifespan dramatically increases LTV).',
                    'benchmark': 'LTV:CAC ≥ 3:1 is the minimum healthy benchmark. 5:1+ is excellent.',
                },
                {
                    'name': 'LTV:CAC Ratio',
                    'icon': '⚖️',
                    'category': 'revenue',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'The fundamental unit economics test: lifetime value vs. cost to acquire.',
                    'full_description': 'LTV:CAC answers: "For every dollar spent acquiring a customer, how many dollars of lifetime value do we get back?" It determines whether the business model is sustainable and how aggressively to invest in growth.',
                    'formula': 'LTV:CAC = Customer LTV / Customer CAC',
                    'why_it_matters': 'Below 1:1 every new customer destroys value. This ratio determines investor confidence, growth investment levels, and channel strategy.',
                    'how_to_improve': 'Improve LTV (higher ARPU, lower churn, better margins). Reduce CAC (better conversion, organic channels, referral loops). Never optimize just one side of the ratio.',
                    'benchmark': '3:1 minimum. 5:1+ excellent. Under 1:1 is a crisis requiring immediate unit economics fix before scaling.',
                },
                {
                    'name': 'Payback Period',
                    'icon': '⏳',
                    'category': 'revenue',
                    'is_group': False,
                    'order': 3,
                    'short_description': 'Months needed to recover the cost of acquiring a customer.',
                    'full_description': 'Payback period is a cash flow metric that determines how long working capital is tied up per customer and how quickly you can reinvest in growth. Short payback periods allow faster compounding reinvestment cycles.',
                    'formula': 'Payback Period = CAC / (ARPU × Gross Margin %)',
                    'why_it_matters': 'Long payback periods mean capital-intensive growth. Companies with short payback periods can reinvest quickly, creating a virtuous growth cycle.',
                    'how_to_improve': 'Increase ARPU. Offer annual billing (collect more cash upfront). Improve gross margin. Reduce CAC through conversion optimization.',
                    'benchmark': 'Under 12 months: excellent. 12–18 months: acceptable for high-growth SaaS. Over 24 months: requires strong balance sheet.',
                },
                {
                    'name': 'Free-to-Paid Conversion Rate',
                    'icon': '🔓',
                    'category': 'revenue',
                    'is_group': False,
                    'order': 4,
                    'short_description': 'Percentage of free or trial users who upgrade to a paid plan.',
                    'full_description': 'Free-to-Paid CVR is the pivotal monetization metric for freemium and free-trial products. A 1pp improvement here can double early-stage revenue. It measures how well your product communicates value, how appropriate your pricing is, and how well your paywall is positioned.',
                    'formula': 'Free-to-Paid CVR = (Users converted to paid / Total free or trial users) × 100',
                    'why_it_matters': 'For PLG products, this is the direct bridge between product engagement and business revenue. It measures monetization efficiency without requiring more acquisition.',
                    'how_to_improve': 'Place paywalls at moments of high perceived value. Create urgency through trial countdowns. Gate features power users need most. Improve the upgrade page with clear value comparison.',
                    'benchmark': 'Freemium: 2–5% average; 5–8% great. Free trial: 15–25% standard; 25–40% excellent.',
                },
                {
                    'name': 'ARPU',
                    'icon': '💲',
                    'category': 'revenue',
                    'is_group': False,
                    'order': 5,
                    'short_description': 'Average Revenue Per (paying) User per month.',
                    'full_description': 'ARPU measures the average monthly revenue per paying user. It is the primary LTV input and reveals whether pricing and packaging are calibrated to the value delivered. Declining ARPU signals pricing pressure or a shift toward lower-tier plans.',
                    'formula': 'ARPU = Total MRR / Total Paying Users',
                    'why_it_matters': 'Growing ARPU without growing user count grows revenue purely through better monetization. It is often the fastest path to improved unit economics.',
                    'how_to_improve': 'Move upmarket to higher-value segments. Add premium plan tiers. Reduce discounting. Introduce usage-based pricing that scales with customer value.',
                    'benchmark': 'Consumer: $5–20/mo. SMB SaaS: $50–200/mo. Mid-market: $500–2K/mo. Enterprise: $2K+/mo.',
                },
            ],
        },
        # ─── SATISFACTION ──────────────────────────────────────────────────────
        {
            'name': 'Satisfaction & Loyalty',
            'icon': '😊',
            'category': 'satisfaction',
            'is_group': True,
            'order': 5,
            'short_description': 'How satisfied and loyal your users are — leading indicators of retention and growth.',
            'full_description': 'Satisfaction metrics capture the subjective user experience alongside objective behavioral metrics. They act as early warning systems: a drop in NPS or CSAT often predicts churn before it shows up in retention data. They also identify advocacy potential — satisfied users are your most powerful growth channel.',
            'formula': '',
            'why_it_matters': 'Satisfaction scores lead behavioral metrics by 1–2 months. Acting on negative sentiment early prevents churn. Promoters drive referrals that lower CAC.',
            'how_to_improve': 'Close the feedback loop: survey, segment responses, identify root causes, fix them, follow up with respondents. Make satisfaction improvement a cross-functional priority.',
            'benchmark': '',
            'children': [
                {
                    'name': 'NPS (Net Promoter Score)',
                    'icon': '⭐',
                    'category': 'satisfaction',
                    'is_group': False,
                    'order': 0,
                    'short_description': 'The likelihood that users recommend your product — the gold-standard loyalty metric.',
                    'full_description': 'NPS asks users: "How likely are you to recommend this product to a friend or colleague?" (0–10 scale). Scores 9–10 are Promoters, 7–8 are Passives, 0–6 are Detractors. NPS = %Promoters − %Detractors. It is the most widely benchmarked satisfaction metric across industries.',
                    'formula': 'NPS = % Promoters − % Detractors\n(Survey: "How likely are you to recommend us?" 0–10)',
                    'why_it_matters': 'Promoters have 2–4× lower churn and generate significant referral traffic. A high NPS is a leading indicator of organic growth through word of mouth. Detractors actively damage your brand.',
                    'how_to_improve': 'Follow up with Detractors to understand pain points. Celebrate and amplify Promoters (testimonials, case studies, referral invitations). Systematically fix the top 3 issues Detractors mention.',
                    'benchmark': 'Consumer apps: >30 is good; >50 is excellent. B2B SaaS: >40 is strong. World-class products (Apple, Airbnb): 60–80+.',
                },
                {
                    'name': 'CSAT (Customer Satisfaction Score)',
                    'icon': '👍',
                    'category': 'satisfaction',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'How satisfied users are with a specific interaction or feature.',
                    'full_description': 'CSAT asks users: "How satisfied are you with [this feature / interaction / support experience]?" on a 1–5 or 1–10 scale. Unlike NPS (which measures overall loyalty), CSAT is transactional — it measures satisfaction at a specific touchpoint, making it ideal for evaluating feature releases, onboarding flows, or support interactions.',
                    'formula': 'CSAT = (Number of satisfied responses / Total responses) × 100\n(Satisfied = typically top 2 scores: 4–5 on a 5-point scale)',
                    'why_it_matters': 'CSAT at specific touchpoints tells PMs exactly where experience gaps exist. A low CSAT on a specific feature despite high usage is a clear signal to investigate and improve.',
                    'how_to_improve': 'Survey immediately after key interactions (feature use, support interaction, onboarding completion). Track CSAT per feature and per user segment. Prioritize improvements to high-traffic, low-CSAT touchpoints.',
                    'benchmark': 'Across industries: 75%+ is good; 85%+ is excellent. Software: average ~78%. Aim to stay above 80% for all core product interactions.',
                },
                {
                    'name': 'CES (Customer Effort Score)',
                    'icon': '💪',
                    'category': 'satisfaction',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'How easy it is for users to accomplish their goal in your product.',
                    'full_description': 'CES asks: "How easy was it to [complete this task / get help / find what you needed]?" on a 1–7 scale (1 = Very Difficult, 7 = Very Easy). Research by CEB shows CES predicts loyalty better than CSAT or NPS for service interactions. High effort creates frustration and churn; low-effort products generate loyalty.',
                    'formula': 'CES = Average score on "How easy was this experience?" (1–7 scale)\nHigh = Easy (good). Low = Difficult (bad).',
                    'why_it_matters': 'Reducing customer effort is one of the most direct ways to reduce churn. Users who struggle repeatedly will leave. Products that make jobs easy create strong habits and word-of-mouth.',
                    'how_to_improve': 'Map the top 5 user jobs-to-be-done. Identify where effort is highest. Simplify those flows. Improve error messages, help docs, and in-app guidance for high-effort moments.',
                    'benchmark': 'Score of 5.5+ on a 7-point scale is good. Aim to reduce low-effort ratings (<4) to under 10% of responses.',
                },
                {
                    'name': 'Support Ticket Volume',
                    'icon': '🎫',
                    'category': 'satisfaction',
                    'is_group': False,
                    'order': 3,
                    'short_description': 'Volume of support requests as a proxy for product confusion and friction.',
                    'full_description': 'Support ticket volume, normalized by active users, is a product quality signal. Rising tickets per MAU indicates the product is creating confusion, friction, or bugs at scale. Categorizing tickets by topic reveals the top product issues that could be fixed to reduce support cost and improve experience.',
                    'formula': 'Tickets per MAU = Monthly support tickets / MAU',
                    'why_it_matters': 'High support volume is expensive and signals UX problems. Each ticket that reveals a fixable product issue is an opportunity to eliminate future tickets at scale.',
                    'how_to_improve': 'Analyze top ticket categories monthly. For each top category: fix the product to prevent the confusion, or improve self-serve help docs to reduce ticket creation.',
                    'benchmark': 'Best-in-class SaaS: under 0.5 tickets per MAU monthly. Rising ticket rate per MAU is a red flag.',
                },
            ],
        },
        # ─── QUALITY ───────────────────────────────────────────────────────────
        {
            'name': 'Product Quality',
            'icon': '🔧',
            'category': 'quality',
            'is_group': True,
            'order': 6,
            'short_description': 'The reliability, performance, and technical health of your product.',
            'full_description': 'Product quality metrics measure the technical underpinnings of user experience. Even a perfectly designed product with great engagement metrics will churn users if it is slow, buggy, or unreliable. Quality metrics protect all other metrics from being undermined by technical issues.',
            'formula': '',
            'why_it_matters': 'Quality issues destroy trust and retention silently. A 1-second increase in page load time can reduce conversions by 7%. Outages directly cost revenue and damage brand reputation.',
            'how_to_improve': 'Set SLOs (Service Level Objectives) for uptime, latency, and error rate. Build monitoring and alerting. Invest in performance optimization and automated testing.',
            'benchmark': '',
            'children': [
                {
                    'name': 'Uptime / Availability',
                    'icon': '🟢',
                    'category': 'quality',
                    'is_group': False,
                    'order': 0,
                    'short_description': 'Percentage of time the product is operational and accessible to users.',
                    'full_description': 'Uptime measures how reliably your product is available. It is typically expressed in "nines" — 99.9% uptime allows ~8.7 hours of downtime per year; 99.99% allows only ~52 minutes. For any business-critical product, uptime is table stakes.',
                    'formula': 'Uptime % = (Total time − Downtime) / Total time × 100',
                    'why_it_matters': 'Downtime directly costs revenue and erodes user trust disproportionately to the time lost. Users remember outages and often churn after repeated incidents.',
                    'how_to_improve': 'Implement redundancy and failover. Set SLOs and SLAs. Build real-time monitoring and automated alerting. Run regular chaos engineering exercises.',
                    'benchmark': 'Consumer SaaS: 99.9% minimum. Business-critical SaaS: 99.95–99.99%. Enterprise: 99.99%+ expected.',
                },
                {
                    'name': 'Error Rate',
                    'icon': '🐛',
                    'category': 'quality',
                    'is_group': False,
                    'order': 1,
                    'short_description': 'Percentage of user actions or API calls that result in an error.',
                    'full_description': 'Error rate tracks the fraction of user interactions, API calls, or page loads that result in an error (4xx client errors, 5xx server errors, unhandled exceptions, or JS crashes). A rising error rate is an early warning sign before it manifests as user complaints or churn.',
                    'formula': 'Error Rate = (Errors in period / Total requests in period) × 100',
                    'why_it_matters': 'Users encountering errors have significantly higher churn probability. Errors on core actions (checkout, sign-up, key features) are especially damaging and should be treated as priority incidents.',
                    'how_to_improve': 'Set up error tracking (Sentry, Datadog). Categorize errors by frequency and user impact. Fix high-frequency errors in the core user journey first.',
                    'benchmark': 'Under 0.1% server error rate (5xx) is a strong standard. Error rate above 1% on any core action warrants immediate investigation.',
                },
                {
                    'name': 'Page Load Time (P95)',
                    'icon': '⚡',
                    'category': 'quality',
                    'is_group': False,
                    'order': 2,
                    'short_description': 'The 95th percentile of page load time — how slow it is for your slowest users.',
                    'full_description': 'P95 page load time measures how long it takes the 95th percentile of users to load the page — i.e., only 5% of users experience slower loads. Using P95 (not average) reveals the experience of your slowest users, who are often the most likely to abandon. Google\'s research shows page load time directly impacts conversion rate and bounce rate.',
                    'formula': 'P95 Load Time = 95th percentile of page load time in the period',
                    'why_it_matters': 'A 1-second improvement in page load can increase conversions by 7%. Fast products also rank higher in Google Search. Performance is a product feature.',
                    'how_to_improve': 'Implement CDN. Optimize images and assets. Lazy load non-critical resources. Reduce JavaScript bundle size. Use server-side rendering for critical pages.',
                    'benchmark': 'P95 under 2 seconds: good. Under 1 second: excellent. Google recommends LCP under 2.5 seconds for "good" Core Web Vitals.',
                },
                {
                    'name': 'Core Web Vitals',
                    'icon': '📐',
                    'category': 'quality',
                    'is_group': False,
                    'order': 3,
                    'short_description': 'Google\'s standardized performance metrics: LCP, FID/INP, and CLS.',
                    'full_description': 'Core Web Vitals are Google\'s standardized set of performance signals: LCP (Largest Contentful Paint — loading speed), INP (Interaction to Next Paint — interactivity), and CLS (Cumulative Layout Shift — visual stability). They directly impact Google Search ranking and user experience quality.',
                    'formula': 'LCP: Time for largest page element to render\nINP: Time from user interaction to visual response\nCLS: Sum of unexpected layout shifts',
                    'why_it_matters': 'Core Web Vitals affect both user experience and SEO ranking. Pages with poor CWV have higher bounce rates and lower search visibility. They are Google\'s primary UX quality signal for ranking.',
                    'how_to_improve': 'LCP: optimize server response time and image loading. INP: reduce JavaScript execution time. CLS: reserve space for dynamic content, avoid layout-shifting ads.',
                    'benchmark': 'LCP < 2.5s: Good. INP < 200ms: Good. CLS < 0.1: Good. Aim for "Good" for all three metrics on all key pages.',
                },
                {
                    'name': 'MTTR (Mean Time to Recovery)',
                    'icon': '🔨',
                    'category': 'quality',
                    'is_group': False,
                    'order': 4,
                    'short_description': 'Average time from incident detection to full service restoration.',
                    'full_description': 'MTTR measures how quickly your team recovers from production incidents — from the moment an issue is detected to when the service is fully restored for all users. Alongside Deployment Frequency, Lead Time, and Change Failure Rate, it is one of the four DORA DevOps metrics that predict software delivery performance.',
                    'formula': 'MTTR = Total downtime in period / Number of incidents in period',
                    'why_it_matters': 'Slow recovery means prolonged user impact, lost revenue, and compounding brand damage. High-performing teams recover in minutes to hours; low-performing teams take days.',
                    'how_to_improve': 'Build runbooks for common incident types. Implement automated alerting with clear escalation paths. Practice incident response drills. Use feature flags for fast rollbacks.',
                    'benchmark': 'Elite DevOps teams: MTTR under 1 hour. High performers: under 1 day. Medium: 1–7 days. Low performers: over 1 week.',
                },
                {
                    'name': 'Deployment Frequency',
                    'icon': '🚀',
                    'category': 'quality',
                    'is_group': False,
                    'order': 5,
                    'short_description': 'How often your team successfully deploys code to production.',
                    'full_description': 'Deployment frequency is a DORA metric measuring how often teams release code to production. High deployment frequency correlates with better quality (smaller changes are easier to test and roll back), faster iteration, and better responsiveness to user feedback. Elite teams deploy multiple times per day.',
                    'formula': 'Deployment Frequency = Number of successful production deployments / Time period',
                    'why_it_matters': 'Teams that deploy more frequently deliver value to users faster, catch bugs earlier, and are better at learning from production feedback. Slow deployment cycles are a silent drag on product velocity and competitiveness.',
                    'how_to_improve': 'Invest in CI/CD pipelines. Reduce PR size (smaller, more frequent merges). Build comprehensive automated test coverage. Use feature flags to separate deployment from release.',
                    'benchmark': 'Elite: multiple times per day. High: once per day to once per week. Medium: once per week to once per month. Low: less than once per month.',
                },
            ],
        },
    ],
}


class Command(BaseCommand):
    help = 'Seed the database with the PM Metrics Tree data'

    def handle(self, *args, **options):
        self.stdout.write('Clearing existing metrics...')
        MetricNode.objects.all().delete()

        self.stdout.write('Seeding metrics tree...')
        create_node(TREE)

        count = MetricNode.objects.count()
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {count} metric nodes.'))
