# Generated by Django 4.2.9 on 2026-02-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('root', 'Root'), ('growth', 'Growth & Acquisition'), ('activation', 'Activation'), ('retention', 'Retention'), ('engagement', 'Engagement'), ('revenue', 'Revenue'), ('satisfaction', 'Satisfaction'), ('quality', 'Product Quality')], default='growth', max_length=50)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('short_description', models.TextField(help_text='One-sentence summary shown on hover or node label.')),
                ('full_description', models.TextField(blank=True, help_text='Detailed explanation of what this metric means.')),
                ('formula', models.TextField(blank=True, help_text='How to calculate this metric (plain text or formula).')),
                ('why_it_matters', models.TextField(blank=True, help_text='Why PMs should care about this metric.')),
                ('how_to_improve', models.TextField(blank=True, help_text='Actionable tips to move this metric in the right direction.')),
                ('benchmark', models.TextField(blank=True, help_text='Industry average or good/great/excellent benchmarks.')),
                ('is_group', models.BooleanField(default=False, help_text='True if this is a category group node rather than a leaf metric.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sibling sort order.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='metrics.metricnode')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
